name: Clean Reads
favicon: null
layout_spectrum: 0.26079
typography_spectrum: 0.5032
title: Clean Reads
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#67686b'
    - '#8bc53f'
    - '#000000'
    - '#ffffff'
    - '#00ff00'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
