name: Clean Reads
favicon: null
layout_spectrum: 0.3327188512776047
typography_spectrum: 0.8227806447539479
title: Clean Reads
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5537123559042811
  lightness: 0.18937583663500845
  saturation: 0.35841021803207695
  rhythmicContrast: 0.06745002698153257
purpose: []
